//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [Serializable]
    public partial class Tareas
    {
        public decimal Codigo_tarea { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_vencimiento { get; set; }
        public decimal Autor { get; set; }
        [XmlIgnore]
        public virtual Usuarios Usuarios { get; set; }
    }
}
